- client/src/main.rs
This sets the application id `APP_ID` through platform specific settings. Also sets the `id` equal to the `APP_ID`.
Useful for targeting by other tools.
> ✨ set application id

- Cargo.lock
- client/Cargo.toml
- client/src/plugin/utils.rs
This removes fuzzy matching of the search query entirely. Instead, only exact (partial) matches will be displayed.
> 🐛 remove fuzzy matching

- client/src/main.rs
- client/src/plugin/brave/history.rs
- client/src/plugin/brave/mod.rs
This plugin will parse your Brave browser history and add it to the bottom of the centerpiece search list. This should give a nice fallback in case no other plugin entries match your search. Furthermore, this is another step on making the omnibox in your browser obsolete :blush:.
The list of history entries is sorted by the `number of visits to a page` followed by the `last visit to a page`.
This resolves #24.
> ✨ Brave history

- Cargo.lock
- client/Cargo.toml
- client/src/cli.rs
- client/src/main.rs
- flake.nix
✨ init cli and surface version information
Fixes #28
Depends on  #49 and is a first step towards an alternative frontend.
Example:
`centerpiece --version`:
```
centerpiece 0.8.0 - 2024-01-21 - ca255f4
```
>  ✨ init cli and surface version information

- client/src/model.rs
- client/src/plugin/applications.rs
Deduplicate desktop entries of the applications plugin
Fix: #63
Alternative: 
Deduplicate at the model level.
> 🐛 applications: deduplicate entries

- Cargo.toml
- client/Cargo.toml
- flake.lock
- flake.nix
- formatter.nix
- services/index-git-repositories/Cargo.toml
Adds `treefmt` through the `treefmt-nix` module.
This allows the following integration:
- `nix fmt`: format the code through `nix fmt`
- `treefmt`: exposes a wrapped, configured `treefmt` inside the `devShell`
- `nix flake check`: check and lint the code locally, or the ci
All of these options use the same configuration and will share evaluation cache.
Initalize with the following formatters/linters:
- deadnix
- nixfmt
- rustfmt
- statix
- taplo
- yamllint
> ✅ add `treefmt` as module, devShell, check, ci integration

- Cargo.lock
- client/Cargo.toml
- client/src/plugin/git_repositories.rs
- client/src/settings.rs
- config.yml
- flake.nix
I've rewritten the config loading logic:
- removed the `config` create in favor of plain `serde_yaml`
- added the default config as bytes to the centerpiece binary to reduce packaging effort
> 🐛 include default config in binary and rewrite config loading

- flake.nix
Add an evaluation check for the `home-manager` module, this is also exposed in the checks attribute and automatically checked in ci.
> ✅  Add evaluation check for the `home-manager` module

- client/src/plugin/git_repositories.rs
- home-manager-module.nix
Expose the `$GIT_DIRECTORY_NAME` environment variable to the git_repositories plugin.
This is useful for setting `app_ids`, or `tmux` session names, for example.
I am not sure about error handling here.
The unwraps are there because:
- We have a git directory, the file name should always succeed.
- It should always be valid Utf8.
We could return an empty string in an error case, that way scripts might still succeed and fill in a default value.
> ✨ plugins: add `$GIT_DIRECTORY_NAME` env variable

- README.md
- client/Cargo.toml
- client/src/cli.rs
- client/src/main.rs
- client/src/plugin/utils.rs
- client/src/settings.rs
Allow specifying the configuration location through:
- `--config` flag
- `CENTERPIECE_CONFIGURATION_FILE` environment variable
> feat: allow specifying configuration location

- services/index-git-repositories/src/main.rs
Since to_str will not fail when the input is ".git" and that input is the only input that matters to us, we can avoid crashing the daemon when to_str returns none.
> return false when file_name cannot convert to str

- client/src/plugin/resource_monitor/cpu.rs
This PR changes the CPU resource monitor plugin to visualize its cores as bars in one line instead of having a line per core. This resolves #104 and fixes #114.
> 💄 display bars to visualize cpu core usage

- client/src/main.rs
This fixes the scrolling issue below #114.
> 🐛 filter empty plugins for calculating scroll offset

- README.md
- client/src/plugin/git_repositories.rs
- client/src/plugin/utils.rs
- client/src/settings.rs
- home-manager-module.nix
Add `zoxide` integration for the `git_repositories` plugin. If enabled and installed will sort the paths by their `zoxide` score.
Closes: #36
> ✨ `git_repositories`: add `zoxide` integration 

- Cargo.lock
- client/Cargo.toml
- client/src/plugin/applications.rs
This PR implements a bunch of fixes around the applications plugin. This aligns the applications plugin closer with the [freedesktop desktop entry specification](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html). Furhtermore it fixes #110.
This PR includes:
- Hiding desktop entries based on the following logic:
- Type has to be "Application"
- Hidden has to be false or unset
- NoDisplay has to be false or unset
- the XDG_CURRENT_DESKTOP has to be in OnlyShowIn and not in NotShowIn
- Terminal desktop entries are now opened in the first terminal emulator that is found on the system (fixes things like btop not being able to launch)
> fix: implement full desktop spec

- client/src/main.rs
- client/src/plugin/applications.rs
- client/src/plugin/brave/bookmarks.rs
- client/src/plugin/brave/progressive_web_apps.rs
- client/src/plugin/sway_windows.rs
- client/src/plugin/utils.rs
This sorts entries in the following plugins after they are updated:
- applications
- sway-windows
- brave-bookmarks
- brave-progressive-web-apps
This fixes the initial sorting on those plugins. Furthermore, this removes the unnecessary sorting on an empty query and it fixes lower vs uppercase sorting problems.
This fixes #122.
> 🐛 fix initial sorting in a bunch of plugins

- Cargo.lock
- client/Cargo.toml
- client/src/component/entry.rs
- client/src/component/query_input.rs
- client/src/main.rs
- client/src/settings.rs
Partly Fixes #108 
I implemented basic color settings trying to follow the other settings. Since I havn't worked with this very much before, I'm sure there is stuff I missed or should be done differently. Please let me know what has to change, any hints very welcome. 
I only implemented colors for now. Not sure if font settings should be a separate PR.
> Allow setting colors via configuration

- README.md
- client/src/main.rs
- client/src/plugin/gitmoji.rs
- client/src/plugin/mod.rs
- client/src/settings.rs
_List gitmojis and copy them._
Note: You need to have [wl-clipboard](https://github.com/bugaevc/wl-clipboard) installed on your system.
**Related config keys**
```yml
plugin:
gitmoji:
enable: false
```
This resolves #21.
> 😜 Gitmoji plugin

- Cargo.lock
- README.md
- client/Cargo.toml
- client/src/main.rs
- client/src/plugin/firefox/bookmarks.rs
- client/src/plugin/firefox/mod.rs
- client/src/plugin/mod.rs
- client/src/settings.rs
- home-manager-module.nix
This finally adds a first plugin for firefox :tada:. With this you are able to search and open your firefox bookmarks. Bookmarks are sorted by the number of visits.
This closes #13!
> 📑 Firefox bookmarks plugin

- client/src/component/entry.rs
- client/src/component/query_input.rs
- client/src/main.rs
- client/src/settings.rs
Add the `get_or_init` function to `[Settings]` that will cache the
result in memory once it reads the settings file from disk.
> 🐛 Change settings to be loaded only once from disk

- Cargo.lock
- client/Cargo.toml
- client/src/component/entry.rs
- client/src/component/plugin_header.rs
- client/src/component/query_input.rs
- client/src/main.rs
After merging https://github.com/friedow/centerpiece/pull/81 I noticed a performance impact while filtering entries in release builds. This is why I reverted this change in https://github.com/friedow/centerpiece/pull/130. 
Feature wise this PR works but I would rather stay on the older version if the new one decreases performance.
> ⬆️ Bump iced from 0.10.0 to 0.12.1

- flake.nix
Update crane library instantiation from the now deprecated invocation.
Reference: https://github.com/ipetkov/crane/releases/tag/v0.17.0
> 🔨 Update crane library instantiation

- Cargo.lock
`rustc --version`: `v1.80.0` has a type inference regression. This causes compilation of `centerpiece` to fail, because we use an affected version of the `time` crate.
This updates the time crate to a released version with a fix.
Reference:
- https://github.com/NixOS/nixpkgs/issues/332957
- https://github.com/rust-lang/rust/issues/125319
- https://github.com/rust-lang/rust/pull/99969
> 🚑️ Fix compilation with `rustc` `v1.80`

- Cargo.lock
- client/Cargo.toml
- client/src/component/divider.rs
- client/src/component/entry.rs
- client/src/component/plugin_header.rs
- client/src/component/query_input.rs
- client/src/main.rs
- client/src/plugin/applications.rs
- client/src/plugin/firefox/utils.rs
- client/src/plugin/utils.rs
- client/src/settings.rs
- flake.lock
- flake.nix
This updates iced to 0.13.1 which overhauls the theming system. The most relevant change in this PR is the removal of the `color.surface` configuration value which has been replaced by automatic shading of the configured background color.
> ⬆️ Update iced from 0.12.1 to 0.13.1

- flake.nix
Remove nixpkgs follow for `crane` flake inputs.
`crane` doesn't depend on `nixpkgs` anymore.
> ➖ Remove nixpkgs follow for crane input

- Cargo.lock
- client/Cargo.toml
- client/src/main.rs
- client/src/settings.rs
This PR fixes a bug where centerpiece was treated as a normal window and not a popup in some wayland window managers like [Niri](https://github.com/YaLTeR/niri). This was fixed by introducing [iced_layershell](https://crates.io/crates/iced-layershell) as a dependency which implements the [wayland layershell protocol](https://wayland.app/protocols/wlr-layer-shell-unstable-v1) for iced.
We had to revert the builder pattern for the iced application which was introduced with the upgrade to iced 0.13.x because iced_layershell does not support that yet.
Special thanks to @Decodetalkers for jumping in and helping me make this happen.
This resolves #188.
> 🐛 fix centerpiece not being an overlay in some wayland WMs

- Cargo.lock
- client/Cargo.toml
- client/src/plugin/resource_monitor/cpu.rs
This change adds temperatures display to centerpiece:
I am initially marking this PR as draft because:
1. I don't want to impose a contribution. If this plugin is not deemed useful/interesting/worth maintaining -- that's totally fine.
2. My Rust skills are at the point where I can write working code but I have never produced code that another person looked at. I completely expect having to rewrite this code and use different idioms/code style.
3. I am not 100% sure about the way I implemented the plugin settings.
By default, just showing all components' temperatures has two problems:
1. There are a lot of sensors, not all of them can be interesting
2. Default labels from sysinfo crate may not be useful at a glance
I have added a list of dictionaries to the settings that allows a user to …
> 🌡️ CPU temperature

- Cargo.lock
- client/Cargo.toml
- client/src/plugin/utils.rs
Adds fuzzy matching via the [nucleo](https://github.com/helix-editor/nucleo) crate. This should be practically as fast, if not faster, than the previous implementation since nucleo does a prefiltering step with `memchr`. It first fuzzy matches against the `title` of the entry, falling back to substring matching against the `meta`. A match on the `title` receives a `+ 1000` to the score to always beat a match on `meta`.
Before:
After:
> Fuzzy matching with nucleo

- client/src/main.rs
Workaround for #237
I believe setting it through nix requires wrapping the program and would generally only benefit nix users. Setting in rust is a bit less hacky and should work for everyone
> Set `WGPU_POWER_PREF` to high when not set
